version = 0.1

[default.deploy.parameters]
stack_name = "call-copilot-poc"
resolve_s3 = true
s3_prefix = "call-copilot-poc"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"prod\" EventBusName=\"CallCopilotBus\" CallStateTableName=\"CallStateTable\" ConnectionsTableName=\"ConnectionsTable\" RecordingsBucketName=\"\""
image_repositories = []

[default.global.parameters]
region = "us-west-2"
